"""check_phase_1

Revision ID: 30767780a812
Revises: 4ff3f26e5857
Create Date: 2025-11-27 16:35:48.903006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30767780a812'
down_revision: Union[str, None] = '4ff3f26e5857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_pages_cache_key'), 'raw_pages', ['cache_key'], unique=False)
    op.create_index(op.f('ix_raw_pages_domain'), 'raw_pages', ['domain'], unique=False)
    op.create_index(op.f('ix_raw_pages_fetched_at'), 'raw_pages', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_pages_url'), 'raw_pages', ['url'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('leagues', sa.JSON(), nullable=True),
    sa.Column('teams', sa.JSON(), nullable=True),
    sa.Column('time_window_days', sa.Integer(), nullable=True),
    sa.Column('force_playwright', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('last_source', sa.String(), nullable=True),
    sa.Column('totals', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_user_id'), 'scrape_jobs', ['user_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('league_code', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('credibility', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_fetched_at'), 'facts', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_facts_job_id'), 'facts', ['job_id'], unique=False)
    op.create_index(op.f('ix_facts_league_code'), 'facts', ['league_code'], unique=False)
    op.create_index(op.f('ix_facts_team'), 'facts', ['team'], unique=False)
    op.create_index(op.f('ix_facts_type'), 'facts', ['type'], unique=False)
    op.create_index(op.f('ix_facts_user_id'), 'facts', ['user_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('league_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('facts_count', sa.Integer(), nullable=True),
    sa.Column('sources_used', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_created_at'), 'snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_snapshots_league_code'), 'snapshots', ['league_code'], unique=False)
    op.create_index(op.f('ix_snapshots_user_id'), 'snapshots', ['user_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('delivery_channel', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_snapshots_user_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_league_code'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_created_at'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_facts_user_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_type'), table_name='facts')
    op.drop_index(op.f('ix_facts_team'), table_name='facts')
    op.drop_index(op.f('ix_facts_league_code'), table_name='facts')
    op.drop_index(op.f('ix_facts_job_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_fetched_at'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_scrape_jobs_user_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_status'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_raw_pages_url'), table_name='raw_pages')
    op.drop_index(op.f('ix_raw_pages_fetched_at'), table_name='raw_pages')
    op.drop_index(op.f('ix_raw_pages_domain'), table_name='raw_pages')
    op.drop_index(op.f('ix_raw_pages_cache_key'), table_name='raw_pages')
    op.drop_table('raw_pages')
    # ### end Alembic commands ###
