"""Add delivery tracking fields

Revision ID: 5edfc5d355d3
Revises: e0793219cd97
Create Date: 2025-11-29 15:39:17.690994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edfc5d355d3'
down_revision: Union[str, None] = 'e0793219cd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('language', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('tone', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('team_focus', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('delivery_status', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('delivery_error', sa.String(), nullable=True))
    op.drop_column('reports', 'status')
    op.add_column('users', sa.Column('last_report_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_report_sent_at')
    op.add_column('reports', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'delivery_error')
    op.drop_column('reports', 'delivery_status')
    op.drop_column('reports', 'sent_at')
    op.drop_column('reports', 'generated_at')
    op.drop_column('reports', 'team_focus')
    op.drop_column('reports', 'tone')
    op.drop_column('reports', 'language')
    # ### end Alembic commands ###
