"""add_source_id_to_match

Revision ID: e0793219cd97
Revises: 30767780a812
Create Date: 2025-11-29 14:51:55.066670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0793219cd97'
down_revision: Union[str, None] = '30767780a812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('source_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_matches_source_id'), 'matches', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_source_id'), table_name='matches')
    op.drop_column('matches', 'source_id')
    # ### end Alembic commands ###
