"""Add frequency preference

Revision ID: e211cf34cd7c
Revises: 5edfc5d355d3
Create Date: 2025-11-29 17:20:31.697292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e211cf34cd7c'
down_revision: Union[str, None] = '5edfc5d355d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frequency')
    # ### end Alembic commands ###
